task: detection

num_classes: 13
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/autodl-tmp/PlantDoc_coco/train2017/images
    ann_file: /root/autodl-tmp/PlantDoc_coco/train2017/instances_train2017.json
    transforms:
      type: Compose
      ops:
        - type: RandomHorizontalFlip
        - type: RandomResize
          sizes: [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
          max_size: 1333
        - type: ToTensor
        - type: Normalize
          mean: [0.485, 0.456, 0.406]
          std:  [0.229, 0.224, 0.225]
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True
val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/autodl-tmp/PlantDoc_coco/val2017/images
    ann_file: /root/autodl-tmp/PlantDoc_coco/val2017/instances_val2017.json
    transforms:
      type: Compose
      ops:
        - type: Resize
          size: 800
          max_size: 1333
        - type: ToTensor
        - type: Normalize
          mean: [0.485, 0.456, 0.406]
          std:  [0.229, 0.224, 0.225]
  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False
